//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.MyOffice.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.MyOffice.Res.S", typeof(S).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ предоставлен.
        /// </summary>
        public static string AccessAllowed {
            get {
                return ResourceManager.GetString("AccessAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить категорию.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить дневной отчет.
        /// </summary>
        public static string AddDayReport {
            get {
                return ResourceManager.GetString("AddDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить файл.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить оплату.
        /// </summary>
        public static string AddPayment {
            get {
                return ResourceManager.GetString("AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить проект.
        /// </summary>
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись.
        /// </summary>
        public static string AddRecord {
            get {
                return ResourceManager.GetString("AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить задачу.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставить доступ.
        /// </summary>
        public static string AllowAccess {
            get {
                return ResourceManager.GetString("AllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все проекты.
        /// </summary>
        public static string AllProjects {
            get {
                return ResourceManager.GetString("AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой офис.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утвержден.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить пароль.
        /// </summary>
        public static string AssignPassword {
            get {
                return ResourceManager.GetString("AssignPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код для установки пароля.
        /// </summary>
        public static string AssignPasswordCode {
            get {
                return ResourceManager.GetString("AssignPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привязать.
        /// </summary>
        public static string Associcate {
            get {
                return ResourceManager.GetString("Associcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ бота.
        /// </summary>
        public static string BotId {
            get {
                return ResourceManager.GetString("BotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC бота.
        /// </summary>
        public static string BotUTC {
            get {
                return ResourceManager.GetString("BotUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через запятую.
        /// </summary>
        public static string ByComma {
            get {
                return ResourceManager.GetString("ByComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string ChangingPassword {
            get {
                return ResourceManager.GetString("ChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} и {1} не совпадают..
        /// </summary>
        public static string CompareAttribute {
            get {
                return ResourceManager.GetString("CompareAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка подключения.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюты.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс.
        /// </summary>
        public static string CurrencyRate {
            get {
                return ResourceManager.GetString("CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы валют.
        /// </summary>
        public static string CurrencyRates {
            get {
                return ResourceManager.GetString("CurrencyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип валюты.
        /// </summary>
        public static string CurrencyType {
            get {
                return ResourceManager.GetString("CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказчик.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задолженность клиента.
        /// </summary>
        public static string CustomerDebt {
            get {
                return ResourceManager.GetString("CustomerDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенты.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задолженность клиентов.
        /// </summary>
        public static string CustomersDebt {
            get {
                return ResourceManager.GetString("CustomersDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код базы даных.
        /// </summary>
        public static string DataBaseId {
            get {
                return ResourceManager.GetString("DataBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базы.
        /// </summary>
        public static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневной отчет.
        /// </summary>
        public static string DayReport {
            get {
                return ResourceManager.GetString("DayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За день.
        /// </summary>
        public static string DayTotals {
            get {
                return ResourceManager.GetString("DayTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоги за день.
        /// </summary>
        public static string DayTotalsShow {
            get {
                return ResourceManager.GetString("DayTotalsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задолженность.
        /// </summary>
        public static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвязать.
        /// </summary>
        public static string Diasssocicate {
            get {
                return ResourceManager.GetString("Diasssocicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить пароль.
        /// </summary>
        public static string DoResetPassword {
            get {
                return ResourceManager.GetString("DoResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование дневного отчета.
        /// </summary>
        public static string EditMemberDayReport {
            get {
                return ResourceManager.GetString("EditMemberDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение оплата.
        /// </summary>
        public static string EditMemberPayment {
            get {
                return ResourceManager.GetString("EditMemberPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансы.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учет личных средств в разрезе статей на различных счетах и в различных валютах.
        /// </summary>
        public static string Finance1 {
            get {
                return ResourceManager.GetString("Finance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты об остатках, поступлениях и расходах.
        /// </summary>
        public static string Finance2 {
            get {
                return ResourceManager.GetString("Finance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансы.
        /// </summary>
        public static string FinanceManager {
            get {
                return ResourceManager.GetString("FinanceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказчику.
        /// </summary>
        public static string ForCustomer {
            get {
                return ResourceManager.GetString("ForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка задач исполнителю.
        /// </summary>
        public static string ForCustomer1 {
            get {
                return ResourceManager.GetString("ForCustomer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчетность исполнителя во временном и денежном выражении.
        /// </summary>
        public static string ForCustomer2 {
            get {
                return ResourceManager.GetString("ForCustomer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фрилансеру.
        /// </summary>
        public static string ForFreelancer {
            get {
                return ResourceManager.GetString("ForFreelancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ведение списка заказчиков и финансовых условий работы.
        /// </summary>
        public static string ForFreelancer1 {
            get {
                return ResourceManager.GetString("ForFreelancer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка задача заказчиком.
        /// </summary>
        public static string ForFreelancer2 {
            get {
                return ResourceManager.GetString("ForFreelancer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учет затрат времени.
        /// </summary>
        public static string ForFreelancer3 {
            get {
                return ResourceManager.GetString("ForFreelancer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учет и отчетность о выполненных объемах работ.
        /// </summary>
        public static string ForFreelancer4 {
            get {
                return ResourceManager.GetString("ForFreelancer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ч..
        /// </summary>
        public static string HoursS {
            get {
                return ResourceManager.GetString("HoursS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я.
        /// </summary>
        public static string IAm {
            get {
                return ResourceManager.GetString("IAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string Implementer {
            get {
                return ResourceManager.GetString("Implementer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задолженность перед исполнителями.
        /// </summary>
        public static string ImplementerDebt {
            get {
                return ResourceManager.GetString("ImplementerDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string Implementers {
            get {
                return ResourceManager.GetString("Implementers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт курсов.
        /// </summary>
        public static string ImportRates {
            get {
                return ResourceManager.GetString("ImportRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЦБ РФ.
        /// </summary>
        public static string ImportRatesCBR {
            get {
                return ResourceManager.GetString("ImportRatesCBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НБ Украины.
        /// </summary>
        public static string ImportRatesNBU {
            get {
                return ResourceManager.GetString("ImportRatesNBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПриватБанка (покупка нал.).
        /// </summary>
        public static string ImportRatesPrivatbank1 {
            get {
                return ResourceManager.GetString("ImportRatesPrivatbank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПриватБанка (продажа нал.).
        /// </summary>
        public static string ImportRatesPrivatbank2 {
            get {
                return ResourceManager.GetString("ImportRatesPrivatbank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в CAPTCHA.
        /// </summary>
        public static string IncorrectCAPTCHA {
            get {
                return ResourceManager.GetString("IncorrectCAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление проектами и финансовый учет выполнения проектов,  учет личный средств..
        /// </summary>
        public static string IndexTopText {
            get {
                return ResourceManager.GetString("IndexTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В работе.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный код.
        /// </summary>
        public static string Invalidtoken {
            get {
                return ResourceManager.GetString("Invalidtoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный email или пароль..
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок.
        /// </summary>
        public static string Limitation {
            get {
                return ResourceManager.GetString("Limitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход с локальной учетной записью.
        /// </summary>
        public static string LocalAccountLogin {
            get {
                return ResourceManager.GetString("LocalAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email не доступен, пожалуйста зарегистрируйтесь .
        /// </summary>
        public static string LoginProviderNoEmail {
            get {
                return ResourceManager.GetString("LoginProviderNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневные отчеты.
        /// </summary>
        public static string MemberDayReports {
            get {
                return ResourceManager.GetString("MemberDayReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задолженность заказчиков.
        /// </summary>
        public static string MemberDebt {
            get {
                return ResourceManager.GetString("MemberDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплаты заказчика.
        /// </summary>
        public static string MemberPayment {
            get {
                return ResourceManager.GetString("MemberPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ставки.
        /// </summary>
        public static string MemberRates {
            get {
                return ResourceManager.GetString("MemberRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string MemberType {
            get {
                return ResourceManager.GetString("MemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string MenuTimeLogger {
            get {
                return ResourceManager.GetString("MenuTimeLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчетсво.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м..
        /// </summary>
        public static string MinitesS {
            get {
                return ResourceManager.GetString("MinitesS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина должна быть не менее {0} знаков.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Движения.
        /// </summary>
        public static string Motions {
            get {
                return ResourceManager.GetString("Motions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти.
        /// </summary>
        public static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя валюта.
        /// </summary>
        public static string MyCurrency {
            get {
                return ResourceManager.GetString("MyCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой профиль.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои проекты.
        /// </summary>
        public static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая категория.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая валюта.
        /// </summary>
        public static string NewCurrency {
            get {
                return ResourceManager.GetString("NewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый клиент.
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый дневной отчет.
        /// </summary>
        public static string NewCustomerDayReport {
            get {
                return ResourceManager.GetString("NewCustomerDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая оплата.
        /// </summary>
        public static string NewCustomerPayment {
            get {
                return ResourceManager.GetString("NewCustomerPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый исполнитель.
        /// </summary>
        public static string NewImplementer {
            get {
                return ResourceManager.GetString("NewImplementer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый участник.
        /// </summary>
        public static string NewMember {
            get {
                return ResourceManager.GetString("NewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый дневной отчет.
        /// </summary>
        public static string NewMemberDayReport {
            get {
                return ResourceManager.GetString("NewMemberDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая оплата.
        /// </summary>
        public static string NewMemberPayment {
            get {
                return ResourceManager.GetString("NewMemberPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый проект.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый курс.
        /// </summary>
        public static string NewRate {
            get {
                return ResourceManager.GetString("NewRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая задача.
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to если у Вас нет локальной учетной записи..
        /// </summary>
        public static string NoLocalAccount {
            get {
                return ResourceManager.GetString("NoLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не принятые.
        /// </summary>
        public static string NotAccepted {
            get {
                return ResourceManager.GetString("NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На.
        /// </summary>
        public static string OnDate {
            get {
                return ResourceManager.GetString("OnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На конец.
        /// </summary>
        public static string OnEnd {
            get {
                return ResourceManager.GetString("OnEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На начало.
        /// </summary>
        public static string OnStart {
            get {
                return ResourceManager.GetString("OnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        public static string Params {
            get {
                return ResourceManager.GetString("Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнер.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнеры.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение не совпадают..
        /// </summary>
        public static string PasswordConfirmationError {
            get {
                return ResourceManager.GetString("PasswordConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплаты.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период с:.
        /// </summary>
        public static string PeriodFrom {
            get {
                return ResourceManager.GetString("PeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив проектов.
        /// </summary>
        public static string ProjectArchive {
            get {
                return ResourceManager.GetString("ProjectArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить.
        /// </summary>
        public static string ProjectRestrore {
            get {
                return ResourceManager.GetString("ProjectRestrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принят.
        /// </summary>
        public static string ProjectStateApproved {
            get {
                return ResourceManager.GetString("ProjectStateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен.
        /// </summary>
        public static string ProjectStateComplete {
            get {
                return ResourceManager.GetString("ProjectStateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В работе.
        /// </summary>
        public static string ProjectStateInProgress {
            get {
                return ResourceManager.GetString("ProjectStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string ProjectStateNew {
            get {
                return ResourceManager.GetString("ProjectStateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принята.
        /// </summary>
        public static string ProjectTaskStateApproved {
            get {
                return ResourceManager.GetString("ProjectTaskStateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершена.
        /// </summary>
        public static string ProjectTaskStateComplete {
            get {
                return ResourceManager.GetString("ProjectTaskStateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В работе.
        /// </summary>
        public static string ProjectTaskStateInProgress {
            get {
                return ResourceManager.GetString("ProjectTaskStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая.
        /// </summary>
        public static string ProjectTaskStateNew {
            get {
                return ResourceManager.GetString("ProjectTaskStateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить рабочую станцию {0}?.
        /// </summary>
        public static string QDeleteTimeLoggerSettingWorkStation {
            get {
                return ResourceManager.GetString("QDeleteTimeLoggerSettingWorkStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстрые записи.
        /// </summary>
        public static string QuickRecords {
            get {
                return ResourceManager.GetString("QuickRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ставка.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ставки.
        /// </summary>
        public static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ставка установлена.
        /// </summary>
        public static string RateSettedAs {
            get {
                return ResourceManager.GetString("RateSettedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить пользователя с e-mail.
        /// </summary>
        public static string ReallyAddUserWithEmail {
            get {
                return ResourceManager.GetString("ReallyAddUserWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочники.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; обязательно для заполнения..
        /// </summary>
        public static string RequiredFormat {
            get {
                return ResourceManager.GetString("RequiredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения.
        /// </summary>
        public static string ResetPasswordCode {
            get {
                return ResourceManager.GetString("ResetPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить пароль.
        /// </summary>
        public static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код восстановления.
        /// </summary>
        public static string RestorePasswordCode {
            get {
                return ResourceManager.GetString("RestorePasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        public static string RestoringPassword {
            get {
                return ResourceManager.GetString("RestoringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записать.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с..
        /// </summary>
        public static string SecondsS {
            get {
                return ResourceManager.GetString("SecondsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделы.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите категорию.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить отчет на.
        /// </summary>
        public static string SendDebtInfo {
            get {
                return ResourceManager.GetString("SendDebtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить отчет себе на.
        /// </summary>
        public static string SendReportToMe {
            get {
                return ResourceManager.GetString("SendReportToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчеты.
        /// </summary>
        public static string Settlements {
            get {
                return ResourceManager.GetString("Settlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кратко.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string Summ {
            get {
                return ResourceManager.GetString("Summ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводная информация.
        /// </summary>
        public static string SummaryInformation {
            get {
                return ResourceManager.GetString("SummaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string SummPay {
            get {
                return ResourceManager.GetString("SummPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммы.
        /// </summary>
        public static string Summs {
            get {
                return ResourceManager.GetString("Summs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string SummWork {
            get {
                return ResourceManager.GetString("SummWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задач.
        /// </summary>
        public static string TaskCount {
            get {
                return ResourceManager.GetString("TaskCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных фиксации времени.
        /// </summary>
        public static string TimeLoggerSettingDataBase {
            get {
                return ResourceManager.GetString("TimeLoggerSettingDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К списку.
        /// </summary>
        public static string ToIndex {
            get {
                return ResourceManager.GetString("ToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь уже существует.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представление.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рады вам.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работы.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция.
        /// </summary>
        public static string WorkStation {
            get {
                return ResourceManager.GetString("WorkStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код станции.
        /// </summary>
        public static string WorkStationId {
            get {
                return ResourceManager.GetString("WorkStationId", resourceCulture);
            }
        }
    }
}
